### ISSUE TITLE
Problem: unit tests fail in py-utils

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-utils#105]
More detailed problem: it seems like it is impossible to run unit tests using setup.py (a preferred pythonic way of doing that).

Steps to reproduce:
1. Clone the repository locally
2. Go to py-utils subfolder
3. Run the following command: `python ./setup.py test`

Expected results: tests run, verdict is OK.

Actual result: failure at the initialization stage:
```
$ python ./setup.py test
running test
/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/dist.py:517: UserWarning: Module argparse was already imported from /usr/lib64/python3.6/argparse.py, but /home/720599/projects/hare/.py3venv/lib/python3.6/site-packages/argparse-1.4.0-py3.6.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/dist.py:517: UserWarning: Module configparser was already imported from /usr/lib64/python3.6/configparser.py, but /home/720599/projects/hare/.py3venv/lib/python3.6/site-packages/configparser-4.0.2-py3.6.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
running egg_info
writing cortx_py_utils.egg-info/PKG-INFO
writing dependency_links to cortx_py_utils.egg-info/dependency_links.txt
writing entry points to cortx_py_utils.egg-info/entry_points.txt
writing requirements to cortx_py_utils.egg-info/requires.txt
writing top-level names to cortx_py_utils.egg-info/top_level.txt
package init file 'src/utils/kvstore/__init__.py' not found (or not a regular file)
reading manifest file 'cortx_py_utils.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cortx_py_utils.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 78, in <module>
    install_requires=get_install_requirements())
  File "/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/lib64/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib64/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/720599/projects/cortx-utils/py-utils/test/test_decision_maker.py", line 31, in <module>
    class TestDecisionMaker(unittest.TestCase):
  File "/home/720599/projects/cortx-utils/py-utils/test/test_decision_maker.py", line 40, in TestDecisionMaker
    _dec_maker = DecisionMaker(decisiondb=mock_decisiondb)
  File "/home/720599/projects/cortx-utils/py-utils/cortx/utils/ha/dm/decision_maker.py", line 112, in __init__
    const.CORTX_HA_INSTALL_PATH, const.RULES_FILE_PATH))
  File "/home/720599/projects/cortx-utils/py-utils/cortx/utils/ha/dm/decision_maker.py", line 36, in __init__
    self._load_rules()
  File "/home/720599/projects/cortx-utils/py-utils/cortx/utils/ha/dm/decision_maker.py", line 47, in _load_rules
    Log.debug(f"Loading rules json into memory. File: {self._rule_file}")
  File "/home/720599/projects/cortx-utils/py-utils/cortx/utils/log.py", line 89, in debug
    Log.logger.debug(f"[{caller}] {msg}", *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'debug'
```

**Comment by yanqingfu** [comment]
[root@ssc-vm-2736 py-utils]# python ./setup.py test
  File "./setup.py", line 46
    def get_install_requirements() -> list:
                                   ^
SyntaxError: invalid syntax

**Comment by veerendra-simha-garikipati** [comment]
To run py-utils unittests we can execute below command, which executes py-utils tests through utils_setup(mini provisiner) test phase
`/opt/seagate/cortx/utils/bin/utils_setup test --plan sanity`

In test phase, with sanity as a plan argument, it will run the sanity test cases present in py-utils-test.

Note: we can run any plan available at 'cortx-utils/py-utils/test/plans/', but as of now these plans were empty, so we can manually add tests and execute the test command, we will add tests in the plans in coming days

Please refer on how to run py-utils tests: https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/test_framework/README.md

cc @sachinpunadikar @rahul-tripathi-git

**Comment by cortx-admin** [comment]
> VEERENDRA GARIKIPATI commented in Jira Server:

To run py-utils unittests we can execute below command, which executes py-utils tests through utils_setup(mini provisiner) test phase
 {{/opt/seagate/cortx/utils/bin/utils_setup test --plan sanity}}

In test phase, with sanity as a plan argument, it will run the sanity test cases present in py-utils-test.

Note: we can run any plan available at 'cortx-utils/py-utils/test/plans/', but as of now these plans were empty, so we can manually add tests and execute the test command, we will add tests in the plans in coming days

Please refer on how to run py-utils tests: [https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/test_framework/README.md]

cc [~744293] [~931627]

**Comment by knekrasov** [comment]
That's good to know @veerendra-simha-garikipati 

But that doesn't sound like a solution. Normally, unit tests is a part of development environment which is by assumed to be comfortable. In other words, as a developer I need to be able to modify the code and run unit tests as soon and easy as possible: this is necessary to make sure that the code works and to ensure that the existing functionality was not broken (i.e. no regression).


The fact that that in order to run the tests one needs to use mini provisioner contradicts the idea of simplicity: the developer needs to wrap the current code into the RPM, install that RPM (presuming that Pythonic dependencies are resolved also - we all remember that cortx-py-utils RPM doesn't manage Pythonic dependencies) and only then run the tests. And I also suppose that mini provisioner script possibly requires root user.

**Comment by veerendra-simha-garikipati** [comment]
@knekrasov 
So to run py-utils unittests without test-RPM or through mini provisioning test phase, we can directly go to particular feature directory under test and run the test_file.py as below:
`python3 test_file.py`

and if we need to run a single test then the below command will help:
`python3 -m unittest test_module.TestClass.test_method`

please correct me if the expectation is different.

**Comment by knekrasov** [comment]
@veerendra-simha-garikipati Here is what I see at the freshest `main` branch

```
$ python -m unittest discover
EEEEEEEE....F...FF................................E...................EEEEEEE..EEEE.EEE..EEF.FF.FFEEEEEEEEEEEEEEEEEE[sudo] password for 720599:
```

Pretty many errors and failures and at some point it started asking for a sudo password.

**Comment by veerendra-simha-garikipati** [comment]
@knekrasov I don't see any break in test execution while running from root user, so I suggest you to run py-utils tests through root
`[root@ssc-vm-rhev4-0917 cortx-utils]# cd py-utils/test/
[root@ssc-vm-rhev4-0917 test]# python3 -m unittest discover
E....F...FF....................................................EEEE..EEEE.EEE..EEF.FF.FFEFEFEFEEEEEEEEEEE....F..Creating mailbox file: File exists
userdel: user utiltester is currently used by process 24222
.useradd: user 'utiltester' already exists
.Creating mailbox file: File exists
.Creating mailbox file: File exists
.Creating mailbox file: File exists
.EEF.....EE.......E.......EEEF.EE.EE.E.E.E....

[--------------------------------------cut here-----------------------------]

----------------------------------------------------------------------
Ran 161 tests in 46.776s
FAILED (failures=14, errors=43)`

and will work on test fixing

**Comment by cortx-admin** [comment]
> VEERENDRA GARIKIPATI commented in Jira Server:

Re-opening this ticket to work on test fixes.

**Comment by veerendra-simha-garikipati** [comment]
@knekrasov Can we close this bug ?
we have another ticket for fixing py-utils unittests - https://jts.seagate.com/browse/EOS-23625

**Comment by knekrasov** [comment]
@veerendra-simha-garikipati 
1. I can see that the tests are still failing (perhaps with some other failures though).
2. The tests require `sudo` (at least according to the discussion above).
3. The unit tests are trying to perform ssh to somewhere.

If you think that it is not a problem, please feel free to close the ticket.

**Comment by sachinpunadikar** [comment]
@knekrasov , 
1. we have started looking into test failures, and will be fixed soon. There is separate ticket for the same.
2. As mentioned, 'sudo' is currently required
3. Will look into SSH thing & update.

**Comment by veerendra-simha-garikipati** [comment]
@knekrasov , @sachinpunadikar 
In py-utils, unittests from the below test scripts are trying to do SSH to localhost, node, hostname to verify the functionalities.
`cortx-utils/py-utils/test/test_ssh_connection.py

cortx-utils/py-utils/test/validator/test_bmc_validator.py
cortx-utils/py-utils/test/validator/test_consul_validator.py
cortx-utils/py-utils/test/validator/test_controller_validator.py
cortx-utils/py-utils/test/validator/test_network_validator.py
cortx-utils/py-utils/test/validator/test_path_validator.py
cortx-utils/py-utils/test/validator/test_service_validator.py`

**Comment by veerendra-simha-garikipati** [comment]
@knekrasov , @sachinpunadikar 
I have updated README file under py-utils/test/ with the list of test scripts that perform ssh to validate functionalities.
hence, closing this issue.

**Comment by cortx-admin** [comment]
> VEERENDRA GARIKIPATI commented in Jira Server:

Resolved
