### ISSUE TITLE
Problem: invalid imports in Validator Framework

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-utils#111]
[Commands](https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/utils/validator/commands.py) in Validator Framework seem to be copied and pasted by the developers and the actual error is being repeated with every new pull request.

In general case, every Command class structure is quite the same to shown below:

```python
class ElasticsearchVCommand(VCommand):
    """Elasticsearch related commands."""

    name = "elasticsearch"

    def __init__(self, args):
        super(ElasticsearchVCommand, self).__init__(args)

        from v_elasticsearch import ElasticsearchV

        self._elasticsearch = ElasticsearchV()

    def process(self):
        """Validate elasticsearch status."""

        self._elasticsearch.validate(self.v_type, self.args)
```

Please notice the line with import.

Problems:
1. Absolute import is invalid. There is no such a package named "v_elasticsearch". Proper way to import the module is one of:
   1. `from .v_elasticsearch import ElasticsearchV` (relative import; please notice the point in the package name)
   2. `from cortx.utils.v_elasticsearch import ElasticsearchV`
2. Imports must be placed at the top of the file (see [PEP-8](https://www.python.org/dev/peps/pep-0008/) standard).

**Note**: the same mistake exists in every Command class, not only in ElasticsearchVCommand.

**Comment by knekrasov** [comment]
The issue is addressed in #85

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

This should be fixed but it is of lower priority.

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

This is a good to have change, the imports in [https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/utils/validator/commands.py] are relative, As per coding standards, the imports should be Absolute and not relative.

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

[~744292] - who owns this PR now as both Rahul Tripathi and knekrasov have left Seagate?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
