### ISSUE TITLE
Problem: python3: can't open file 'setup.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-utils#154]
While following along with this guide https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md I run the first command in this section https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md#build I get the error python3: can't open file 'setup.py': [Errno 2] No such file or directory.

**Comment by sachinpunadikar** [comment]
Hello Patrick,
I hope you have not missed to clone the repo:
$ git clone --recursive https://github.com/Seagate/cortx-utils -b main
After that you will find setup.py in "cortx-utils/py-utils" as below:
-bash-4.2$ ls -al
total 32
drwxrwxr-x 5 744293 744293  252 Jan 15 03:27 .
drwxrwxr-x 7 744293 744293  258 Jan  8 02:28 ..
drwxrwxr-x 3 744293 744293   16 Jan  6 20:23 docs
-rw-rw-r-- 1 744293 744293    0 Jan  6 20:23 __init__.py
-rw-rw-r-- 1 744293 744293   67 Jan  6 20:23 LICENSE
-rw-rw-r-- 1 744293 744293   68 Jan  6 20:23 MANIFEST.in
-rw-rw-r-- 1 744293 744293 3329 Jan  6 20:23 README.md
-rw-rw-r-- 1 744293 744293  274 Jan  6 20:23 requirements.txt
-rw-rw-r-- 1 744293 744293 3441 Jan 15 03:27 setup.py
drwxrwxr-x 4 744293 744293   90 Jan  6 20:23 src
drwxrwxr-x 8 744293 744293 4096 Jan  6 20:23 test
-rwxrwxr-x 1 744293 744293  147 Jan  6 20:23 utils-post-install
-rwxrwxr-x 1 744293 744293  155 Jan  6 20:23 utils-pre-uninstall

Please recheck

**Comment by yanqingfu** [comment]
same issue here, after follow @sachinpunadikar 's instruction, no error
