### ISSUE TITLE
What does this URL point to? Is it needed at all? 

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-utils#175]
https://github.com/Seagate/cortx-utils/blob/3a7f07c0b89d56c1bb5535fa840451fdb6f2dc21/statsd-utils/jenkins/stats_utils.spec#L7

**Comment by shailesh-vaidya** [comment]
@raikrahul  Thanks for raising this. Raised https://github.com/Seagate/cortx-utils/pull/177 to update latest URL.
