### ISSUE TITLE
$ sudo yum install openssl-devel $ sudo yum install libffi-devel error

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-utils#229]
[root@ssc-vm-1061 cortx]# yum install openssl-devel
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-
              : disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscripti             on-manager to register.
**No package openssl-devel available.**
Error: Nothing to do
Uploading Enabled Repositories Report
[root@ssc-vm-1061 cortx]# yum install libffi-devel
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-
              : disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscripti             on-manager to register.
**No package libffi-devel available.**
Error: Nothing to do
Uploading Enabled Repositories Report

**Comment by hessio** [comment]
Hi @yanqingfu could you try running: 

`sudo yum clean all` 

`sudo yum update -y`  
and please let me know if it is still not working after this. I think that your yum repos are not up to date.

**Comment by yanqingfu** [comment]
Hi @hessio after I change a new cloud centos 7.8, it works
