### ISSUE TITLE
Separate test code in optional test rpm 

### ISSUE THREAD

**Issue by ujjwalpl** [Seagate/cortx-utils#239]
Need to separate test code in optional test rpm so its not installed on the production. 
This requires
1. test_framework
2. move test code to a directory 
3. create test rpm.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

We have changed code structure to have separate RPM for test code.
[~933649] please confirm and if we have done all the required actions, please close this bug

**Comment by veerendra-simha-garikipati** [comment]
The required actions were completed, this can be closed.

**Comment by sachinpunadikar** [comment]
Thanks for update, closing it.

**Comment by cortx-admin** [comment]
> VEERENDRA GARIKIPATI commented in Jira Server:

Requirements were done.

**Comment by cortx-admin** [comment]
> VEERENDRA GARIKIPATI commented in Jira Server:

Can be closed.

**Comment by cortx-admin** [comment]
> VEERENDRA GARIKIPATI commented in Jira Server:

Closing.
