### ISSUE TITLE
No module named cortx.utils.security.cipher

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-utils#271]
tried from cortx.utils.security.cipher import Cipher as in https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md

gives error

[root@ssc-vm-2736 cortx-utils]# python
Python 2.7.5 (default, Nov 16 2020, 22:23:17)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cortx.utils.security.cipher import Cipher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cortx.utils.security.cipher

**Comment by hessio** [comment]
Hi @yanqingfu can send me the result of `cat /etc/redhat-release/` please so I can try to reproduce this error on my machine?

**Comment by yanqingfu** [comment]
@hessio CentOS Linux release 7.8.2003 (Core)

**Comment by hessio** [comment]
Hi @yanqingfu looks like the only thing you need to do is run `python3` instead of `python` and your issue should be resolved, please let me know if this does not work.

**Comment by yanqingfu** [comment]
@hessio that works
