### ISSUE TITLE
pip3 install cortx_py_utils-1.0.0-py3-none-any.whl error

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-utils#305]
[root@ssc-vm-2736 dist]# pip3 install cortx_py_utils-1.0.0-py3-none-any.whl
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Processing ./cortx_py_utils-1.0.0-py3-none-any.whl
Collecting schematics==2.1.0
  Downloading schematics-2.1.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 1.4 MB/s
Collecting confluent-kafka==1.5.0
  Downloading confluent_kafka-1.5.0-cp36-cp36m-manylinux1_x86_64.whl (8.1 MB)
     |████████████████████████████████| 8.1 MB 4.2 MB/s
Collecting networkx==2.4
  Downloading networkx-2.4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 39.6 MB/s
Collecting numpy==1.19.2
  Downloading numpy-1.19.2-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 75.9 MB/s
Collecting toml==0.10.0
  Downloading toml-0.10.0-py2.py3-none-any.whl (25 kB)
Collecting python-consul==1.1.0
  Downloading python_consul-1.1.0-py2.py3-none-any.whl (24 kB)
Collecting elasticsearch==6.8.1
  Downloading elasticsearch-6.8.1-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 2.8 MB/s
Collecting paramiko==2.7.1
  Downloading paramiko-2.7.1-py2.py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB 64.3 MB/s
Collecting PyYAML==5.1.2
  Downloading PyYAML-5.1.2.tar.gz (265 kB)
     |████████████████████████████████| 265 kB 84.6 MB/s
Collecting aiohttp==3.6.1
  Downloading aiohttp-3.6.1-cp36-cp36m-manylinux1_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 70.5 MB/s
Collecting elasticsearch-dsl==6.4.0
  Downloading elasticsearch_dsl-6.4.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 2.7 MB/s
Collecting configparser==4.0.2
  Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting matplotlib==3.1.3
  Downloading matplotlib-3.1.3-cp36-cp36m-manylinux1_x86_64.whl (13.1 MB)
     |████████████████████████████████| 13.1 MB 75.8 MB/s
Collecting cryptography==2.8
  Downloading cryptography-2.8-cp34-abi3-manylinux2010_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 78.0 MB/s
Collecting python-crontab==2.5.1
  Downloading python-crontab-2.5.1.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 3.6 MB/s
Collecting idna-ssl>=1.0
  Downloading idna-ssl-1.1.0.tar.gz (3.4 kB)
Collecting chardet<4.0,>=2.0
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 83.8 MB/s
Collecting attrs>=17.3.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 267 kB/s
Collecting async-timeout<4.0,>=3.0
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.6.3-cp36-cp36m-manylinux2014_x86_64.whl (293 kB)
     |████████████████████████████████| 293 kB 63.7 MB/s
Collecting multidict<5.0,>=4.5
  Downloading multidict-4.7.6-cp36-cp36m-manylinux1_x86_64.whl (148 kB)
     |████████████████████████████████| 148 kB 82.7 MB/s
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.6/site-packages (from cryptography==2.8->cortx-py-utils==1.0.0) (1.14.0)
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.5-cp36-cp36m-manylinux1_x86_64.whl (401 kB)
     |████████████████████████████████| 401 kB 77.0 MB/s
Collecting urllib3>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 82.4 MB/s
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 79.8 MB/s
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 9.2 MB/s
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 64.4 MB/s
Collecting decorator>=4.3.0
  Downloading decorator-5.0.9-py3-none-any.whl (8.9 kB)
Collecting pynacl>=1.0.1
  Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
     |████████████████████████████████| 961 kB 62.9 MB/s
Collecting bcrypt>=3.1.3
  Downloading bcrypt-3.2.0-cp36-abi3-manylinux2010_x86_64.whl (63 kB)
     |████████████████████████████████| 63 kB 478 kB/s
Collecting requests>=2.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 6.7 MB/s
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 89.4 MB/s
Collecting idna>=2.0
  Downloading idna-3.1-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 3.8 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 89.6 MB/s
Collecting idna>=2.0
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 710 kB/s
Building wheels for collected packages: python-crontab, PyYAML, idna-ssl
  Building wheel for python-crontab (setup.py) ... done
  Created wheel for python-crontab: filename=python_crontab-2.5.1-py3-none-any.whl size=25596 sha256=1044e6e44ffecaba17595aa87f2457ded971a098f66760e4b301c837ad9d1160
  Stored in directory: /root/.cache/pip/wheels/a2/ac/42/fd4e5a60ce1c981e89387526c837b89a023ef18e620975a84e
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=446925 sha256=1e913e8456c457ad012a4b09f9e1f552217cdbeae95f1a2a0c003595251f0d3d
  Stored in directory: /root/.cache/pip/wheels/d8/9b/e7/75af463b873c119dd444151fc54a8e190c87993593e1fa194a
  Building wheel for idna-ssl (setup.py) ... done
  Created wheel for idna-ssl: filename=idna_ssl-1.1.0-py3-none-any.whl size=3160 sha256=3bfce40dc15d389e1c21173addf0b5cd49645b33ee47cb8a18d0749a911e1ec0
  Stored in directory: /root/.cache/pip/wheels/6a/f5/9c/f8331a854f7a8739cf0e74c13854e4dd7b1af11b04fe1dde13
Successfully built python-crontab PyYAML idna-ssl
Installing collected packages: pycparser, urllib3, typing-extensions, multidict, idna, chardet, cffi, certifi, yarl, requests, python-dateutil, pyparsing, pynacl, numpy, kiwisolver, idna-ssl, elasticsearch, decorator, cycler, cryptography, bcrypt, attrs, async-timeout, toml, schematics, PyYAML, python-crontab, python-consul, paramiko, networkx, matplotlib, elasticsearch-dsl, confluent-kafka, configparser, aiohttp, cortx-py-utils
  Attempting uninstall: numpy
    Found existing installation: numpy 1.12.1
    Uninstalling numpy-1.12.1:
      Successfully uninstalled numpy-1.12.1
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by hessio** [comment]
What version of pip did you use? and also what version of CentOS did you, I used CentOS 7.9.2009 and I was able to get this to work. My version of CentOS:  
 

```
[root@localhost dist]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```

My pip version:

```
[root@localhost dist]# pip3 -V
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
[root@localhost dist]#
```

**Comment by yanqingfu** [comment]
@hessio 

my config:


[root@ssc-vm-2736 dist]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
[root@ssc-vm-2736 dist]# pip3 -V
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 21.1.2 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

**Comment by yanqingfu** [comment]
tried this method and works now
https://stackoverflow.com/questions/49911550/how-to-upgrade-disutils-package-pyyaml

  Attempting uninstall: numpy
    Found existing installation: numpy 1.12.1
    Uninstalling numpy-1.12.1:
      Successfully uninstalled numpy-1.12.1
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
[root@ssc-vm-2736 dist]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
[root@ssc-vm-2736 dist]# pip3 -V
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 21.1.2 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
[root@ssc-vm-2736 dist]# pip install --ignore-installed PyYAML
Collecting PyYAML
  Downloading PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)
     |████████████████████████████████| 640 kB 3.4 MB/s
Installing collected packages: PyYAML
Successfully installed PyYAML-5.4.1
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
[root@ssc-vm-2736 dist]#

**Comment by hessio** [comment]
Oh cool fix thanks for the update @yanqingfu :)
