### ISSUE TITLE
Confusion of build version number for RPM : cortx-utils/py-utils/README.md

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-utils#343]
Hi, 

Should we using the version same like the one mention in `jenkins `command ?

In the readme mentioned

```
$ ./jenkins/build.sh -v 2.0.0 -b 2
```

instead of  mentioned  
`$ yum install -y cortx-py-utils-1.0.0-1.noarch.rpm`, 
use
`$ yum install -y cortx-py-utils-2.0.0-2_<git-version>.noarch.rpm`

**Comment by sachinpunadikar** [comment]
Commit https://github.com/Seagate/cortx-utils/commit/a5a514ee7aff3b802f37cf2100b0714e05e5c983 addresses this issue.

**Comment by sachinpunadikar** [comment]
Closing.
