### ISSUE TITLE
Broken Codacy Badge on cortx-utils/py-utils/README.md

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-utils#344]
The Codacy badge link in [cortx-utils/py-utils/README.md](https://github.com/Seagate/cortx-utils/edit/main/py-utils/README.md) seem like broken.

Look like it point to another [py-utils](https://github.com/Seagate/cortx-py-utils) project which could be no longer active after `py-utils` move to `Seagate/cortx-utils`.

Perhaps just need to point it to `cortx-utils` link and it should work.

**Comment by sachinpunadikar** [comment]
@pujamudaliar please fix this codacy link issue

**Comment by kiwionly2** [comment]
issue fixed.

**Comment by mukul-seagate11** [comment]
Broken has been fixed in https://github.com/Seagate/cortx-utils/pull/399
