### ISSUE TITLE
Inaccurate info on Kafka-Server-Setup

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-utils#345]
Hi, 

I am install `kafka` by follow the [documentation](https://github.com/Seagate/cortx-utils/wiki/Kafka-Server-Setup) and found that in section **Kafka 1 node Setup** 

`cd centos-7.8.2003-2.0.0-latest/commons/kafka`

should be `cd centos-7.8.2003-2.0.0-8/commons/kafka` or `cd centos-7.8.2003-2.0.0-<latest>/commons/kafka`  instead.

This should provide more accurate info.

**Comment by sachinpunadikar** [comment]
@selvakumaar5496 Please fix this.

**Comment by mengwanguc** [comment]
I also encountered similar issue, and I've fixed it in the wiki.

**Comment by kiwionly2** [comment]
issue fixed.
