### ISSUE TITLE
instruction on how to install Python dependencies for cortx-py-utils are missing

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx-utils#362]
In https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md there is

> Installation with RPM package Note : The rpm package installation will fail if any dependent python package is not installed. Please refer to WIKI (https://github.com/Seagate/cortx-utils/wiki/%22cortx-py-utils%22-single-node-manual-provisioning)

The page linked doesn't clarify what has to be done _exactly_ to install `cortx-py-utils` rpm. I see only

```
Required python packages
Refer Required python packages to get the list of required python packages.

Install cortx-py-utils rpm
Get the rpm.
#yum install -y cortx-py-utils-2.0.0-90_8b3c613.noarch.rpm <== RPM name would be different``` which has a broken link and that's it.

**Comment by daniarherikurniawan** [comment]
I agree with this. Looking forward to the update! 
In the meantime, I will try to find the solution myself, but I believe you guys already had the script to handle these dependencies. 
cc: @sachinpunadikar @rahul-tripathi-git

**Comment by sachinpunadikar** [comment]
Updated the WIKI (https://github.com/Seagate/cortx-utils/wiki/%22cortx-py-utils%22-single-node-manual-provisioning) with details, which should help in installing the required python packages:
Required python packages
Refer required python packages from list 1 and list 2 to get the list of required python packages. (Use the above mentioned requirements files in the same order).
Download these files and use below commands to install these python packages
# sudo pip3 install -r <local-path>/python_requirements.txt
# sudo pip3 install -r <local-path>/python_requirements.ext.txt

**Comment by sachinpunadikar** [comment]
If above is good, please close this issue

**Comment by daniarherikurniawan** [comment]
Hi @sachinpunadikar , the Readme is already complicated, so it's better if we simplify it. If those 2 lines is the only line needed, we can just put it in the readme directly. I suggested this PR https://github.com/Seagate/cortx-utils/pull/371/files

**Comment by sachinpunadikar** [comment]
PR #371 merged, WIKI has been updated.
Closing this issue
