### ISSUE TITLE
Separate ConfInit  class from message.py

### ISSUE THREAD

**Issue by ajay-paratmandali** [Seagate/cortx-utils#38]
https://github.com/Seagate/cortx-utils/blob/02bd39f1ed820c65049c7d501512c295694eaecc/py-utils/src/utils/message_bus/message.py#L25

In future
separate ConfInit from message.py file so that other can also use as per requirement.

**Comment by rahul-tripathi-git** [comment]
This file Dont exist anynore
Invalid issue.

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

Not valid

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

Not valid

**Comment by cortx-admin** [comment]
> Selva Kumar Nambi commented in Jira Server:

Ticket not valid
