### ISSUE TITLE
In Elasticsearch storage implementation file: get() method can retrieve only first 10 records. 

### ISSUE THREAD

**Issue by Pranali04796** [Seagate/cortx-utils#54]
This method must retrieve all the records that match to query but retrieving only first 10 records.

https://github.com/Seagate/cortx-utils/blob/3aa95e196e6faacf73d3838ff7f0e7d73689393b/py-utils/src/utils/data/db/elasticsearch_db/storage.py#L464-L467
 We are facing this issue because for elasticsearch **Search API : The default size parameter (number of records actually returned) is 10.**
https://github.com/Seagate/cortx-utils/blob/3aa95e196e6faacf73d3838ff7f0e7d73689393b/py-utils/src/utils/data/db/elasticsearch_db/storage.py#L275

**Comment by cortx-admin** [comment]
> Pranay Kumar commented in Jira Server:

ES is now not part of CORTX

**Comment by cortx-admin** [comment]
> Pranay Kumar commented in Jira Server:

No work

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

Closing this.
