### ISSUE TITLE
error when running "./jenkins/build.sh"

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx-utils#653]
I'm having this error when running `./jenkins/build.sh -v 2.0.0 -b 2` following README:
```

Processing files: cortx-py-utils-2.0.0-2_f66348c.noarch
error: File not found: /root/cortx-utils/py-utils/build/bdist.linux-x86_64/rpm/BUILDROOT/cortx-py-utils-2.0.0-2_f66348c.x86_64/root/anaconda3/lib/python3.9/site-packages/cortx/utils/message_bus/__pycache__/message_broker_collection.cpython-39.pyc
error: File not found: /root/cortx-utils/py-utils/build/bdist.linux-x86_64/rpm/BUILDROOT/cortx-py-utils-2.0.0-2_f66348c.x86_64/root/anaconda3/lib/python3.9/site-packages/cortx/utils/message_bus/__pycache__/message_broker_collection.cpython-39.opt-1.pyc


RPM build errors:
    File not found: /root/cortx-utils/py-utils/build/bdist.linux-x86_64/rpm/BUILDROOT/cortx-py-utils-2.0.0-2_f66348c.x86_64/root/anaconda3/lib/python3.9/site-packages/cortx/utils/message_bus/__pycache__/message_broker_collection.cpython-39.pyc
    File not found: /root/cortx-utils/py-utils/build/bdist.linux-x86_64/rpm/BUILDROOT/cortx-py-utils-2.0.0-2_f66348c.x86_64/root/anaconda3/lib/python3.9/site-packages/cortx/utils/message_bus/__pycache__/message_broker_collection.cpython-39.opt-1.pyc
error: command 'rpmbuild' failed with exit status 1
```

Any suggestions?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27010. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Hi @mengwanguc I am not sure myself I have never had this issue, tagging @rahul-tripathi-git to see if he can help

**Comment by rahul-tripathi-git** [comment]
Hi @mengwanguc 
Can you please share the exact steps to reproduce this issue?

**Comment by mengwanguc** [comment]
> Hi @mengwanguc Can you please share the exact steps to reproduce this issue?

Sure I will do it in one day or two

**Comment by mengwanguc** [comment]
> Hi @mengwanguc Can you please share the exact steps to reproduce this issue?

Tried it again and I'm not having this problem any more... Thus I'm closing this issue. Thanks all!

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

Invalid bug

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

Invalid bug. Cant be reproduced. Reporter closed the issue on github.

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

Invalid bug.
