### ISSUE TITLE
Use HttpService in consul validator

### ISSUE THREAD

**Issue by shrimetta** [Seagate/cortx-utils#84]
Need to update the validation logic in consul validator to make use of HttpService.

**Comment by justinzw** [comment]
@shrimetta is this still valid, it looks like the fix has been merged. Can we close it?

**Comment by shrimetta** [comment]
Yes this is implemented. Closing it.

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

This issue was created as a shadow of [https://github.com/Seagate/cortx-utils/issues/84]. That Github issue has now been closed; this Jira Server ticket can now also be closed.

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

This issue was created as a shadow of [https://github.com/Seagate/cortx-utils/issues/84]. That Github issue has now been closed; this Jira Server ticket can now also be closed.

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

The issue is already fixed in main and Githib issue is also marked as resolved.
